merge: support ignore param to diff function
inveniosoftware/dictdiffer pull request #157
Opened 2021-04-18 06:04 UTC by mafrosis

My use-case requires the `ignore` param when diffing dictionaries.

I started using `Merger` today, and found this option was missing in that class.

2021-04-19 15:31 UTC, joesolly approved these changes

2021-06-21 20:31 UTC, mafrosis commented
Unfortunately I trashed my branch after @joesolly left his approval 😄 

The code is fixed now - and it's quite a trivial change - looking forward to seeing this in a release sometime soon!

2021-06-21 21:02 UTC, joesolly approved these changes

2021-07-05 05:05 UTC, mikaelho reviewed
Nice and simple fix with a test.

While I am not a maintainer, I would think that also adding an update to the docs (updating the docstring) would make this PR easier to merge.

2021-07-13 20:45 UTC, mafrosis commented
@jirikuncar What's stopping this from merging? Docs? Anything else?

2021-07-16 09:26 UTC, jirikuncar commented on dictdiffer/merge.py
> +                 path_limits=[], additional_info=None, ignore=None):
please add `ignore` to docstring

```
: param ignore: ....
```

2021-07-16 09:26 UTC, jirikuncar requested changes
Docstring needs to be updated. Otherwise it looks good 👍

2021-07-16 21:17 UTC, mafrosis commented
Docstring added 🌞

2022-08-22 05:54 UTC, jayvdb commented
ping @markgras @jirikuncar @adrien-berchet

2022-08-22 05:55 UTC, jayvdb approved these changes

2022-08-22 08:28 UTC, adrien-berchet approved these changes
Hi there,
I never used the `Merger` class but that looks like a missing feature indeed.
LGTM!

2022-08-22 13:02 UTC, markgras commented
> ping @markgras @jirikuncar @adrien-berchet

Not too sure why I was included, but I will nevertheless give my two cents. Clean changes with no style guide infractions, updated docstring, and new unittest. Excellent contribution!

2022-08-22 15:22 UTC, jirikuncar approved these changes

2022-08-22 15:23 UTC, merged